### ISSUE TITLE
change name of branch from master to main

### ISSUE THREAD

**Issue by montoyamoraga** [monome/norns-community#84]
according to the discussion here
https://github.com/github/renaming

**Comment by ngwese** [comment]
Changing the default branch in this repository is something which has been is planned. 

While a concerted effort has been made to switch repositories to use more inclusive terms terms this repository has lagged because at the time it would have required first distributing updated configuration to each norns devices so that catalog updates would continue to function. It appears as if there are now sufficient redirection hooks in place on GH to make this change w/o breaking devices.

**Comment by ngwese** [comment]
fixed.
